config/routes.rb
Rails.application.routes.draw do
	root 'hikes#index'
	resources :hikes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hike.rb
class Hike < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
	def index
		@hikes = Hike.all
	end

	def new
		@hike = Hike.new
	end

	def create
		@hike = Hike.create(hike_params)
		redirect_to hike_path(@hike)
	end

	def show
		@hike = Hike.find(params[:id])
	end

	private

	def hike_params
		params.require(:hike).permit(:name, :date, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/views/hikes/index.html.erb
<% @hikes.each do |hike| %>
	<div class ="BoxWithShadow col-10 offset-1">
			<h2><%= hike.name %></h2>
			<p><b><%= hike.date %></b></p>
			<p><%= hike.description %></p>
	</div>

<% end %>

app/views/hikes/new.html.erb
<div class="BoxWithShadow col-10 offset-1">

	<h2>Add a Hike</h2>
	<br />
	<%= simple_form_for @hike do |f| %>
		<%= f.input :name %>
		<%= f.input :date %>
		<%= f.input :description, as: :text %>
		<div class="float-right">
			<%= f.button :submit, class: 'btn btn-success' %>
		</div>
	<% end %>
	<br /><br class="clear" />
</div>

app/views/hikes/show.html.erb
<div class="BoxWithShadow col-10 offset-1">
	<h2><%= @hike.name %></h2>
	<p><b><%= @hike.date %></b></p>
	<p><%= @hike.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colorado Hikes Catalog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Colorado Hikes Catalog', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Add a Hike', new_hike_path, class: 'nav-link' %>
          </li>
        </ul>

      </div>
    </nav>

    <%= yield %>
  </body>
</html>